#EX.4)
I_DNA = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"
I_DNA_E1 = I_DNA[0:64]
I_DNA_E2 = I_DNA[91:200]
print(I_DNA_E1)
print(I_DNA_E2)

from __future__ import division
I_DNA = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"
I_DNA_E1 = I_DNA[0:64]
I_DNA_E2 = I_DNA[91:200]
print(I_DNA_E1)
print(I_DNA_E2)
E1 = len(I_DNA_E1)
E2 = len(I_DNA_E2)
I_DNA_len = len(I_DNA)
(E1 + E2)/ I_DNA_len

from __future__ import division
I_DNA = "ATCGATCGATCGATCGACTGACTAGTCATAGCTATGCATGTAGCTACTCGATCGATCGATCGATCGATCGATCGATCGATCGATCATGCTATCATCGATCGATATCGATGCATCGACTACTAT"
I_DNA_E1 = I_DNA[0:64]
I_DNA_E2 = I_DNA[91:200]
I_DNA_I1 = I_DNA[64:91]
I_DNA_I1_lower = I_DNA_I1.lower()
I_DNAcc = I_DNA_E1 + I_DNA_I1_lower + I_DNA_E2
print(I_DNAcc)
